//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CF_ASP_NET.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CrowdfundingEntities : DbContext
    {
        public CrowdfundingEntities()
            : base("name=CrowdfundingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CfAccount> CfAccount { get; set; }
        public virtual DbSet<CfAccount2> CfAccount2 { get; set; }
        public virtual DbSet<CfBank> CfBank { get; set; }
        public virtual DbSet<CfBulletin> CfBulletin { get; set; }
        public virtual DbSet<CfDirectory> CfDirectory { get; set; }
        public virtual DbSet<CfDirFile> CfDirFile { get; set; }
        public virtual DbSet<CfFile> CfFile { get; set; }
        public virtual DbSet<CfImage> CfImage { get; set; }
        public virtual DbSet<CfImageWebp> CfImageWebp { get; set; }
        public virtual DbSet<CfInvestment> CfInvestment { get; set; }
        public virtual DbSet<CfMember> CfMember { get; set; }
        public virtual DbSet<CfProposal> CfProposal { get; set; }
        public virtual DbSet<CfProposalComment> CfProposalComment { get; set; }
        public virtual DbSet<CfProposalGoal> CfProposalGoal { get; set; }
        public virtual DbSet<CfProposalPromotion> CfProposalPromotion { get; set; }
        public virtual DbSet<CfProposalV> CfProposalV { get; set; }
        public virtual DbSet<CfProposalVerify> CfProposalVerify { get; set; }
        public virtual DbSet<CfVideo> CfVideo { get; set; }
    }
}
