//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CF_ASP_NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CfProposal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CfProposal()
        {
            this.CfInvestment = new HashSet<CfInvestment>();
            this.CfProposalV = new HashSet<CfProposalV>();
            this.CfProposalPromotion = new HashSet<CfProposalPromotion>();
            this.CfProposalGoal = new HashSet<CfProposalGoal>();
            this.CfProposalVerify = new HashSet<CfProposalVerify>();
            this.CfProposalComment = new HashSet<CfProposalComment>();
        }
    
        public int id { get; set; }
        public Nullable<int> member { get; set; }
        public Nullable<int> bank { get; set; }
        public System.DateTime makeTime { get; set; }
        public System.DateTime lastTime { get; set; }
        public string stEnable { get; set; }
    
        public virtual CfBank CfBank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CfInvestment> CfInvestment { get; set; }
        public virtual CfMember CfMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CfProposalV> CfProposalV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CfProposalPromotion> CfProposalPromotion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CfProposalGoal> CfProposalGoal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CfProposalVerify> CfProposalVerify { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CfProposalComment> CfProposalComment { get; set; }
    }
}
